'use client'

import { useState } from 'react'
import { SendHorizontal, Save, Loader2 } from 'lucide-react'
import { Button } from '@workspace/ui/components/button'
import { Textarea } from '@workspace/ui/components/textarea'
import { Checkbox } from '@workspace/ui/components/checkbox'
import { PromptChips } from './PromptChips'
import { useRouter } from 'next/navigation'
import { useTripStore } from '@/lib/store'

import { experimental_useObject as useObject } from '@ai-sdk/react'
import { z } from 'zod'

const itinerarySchema = z.object({
  itinerary: z.array(
    z.object({
      day: z.number(),
      title: z.string(),
      description: z.string(),
      activities: z.array(z.string()),
      imageSearchQuery: z.string().optional(),
    })
  ),
  checklist: z.array(z.string()).optional(),
})

import { Timeline } from './Timeline'

export function ChatInput() {
  const [input, setInput] = useState('')
  const [checkedItems, setCheckedItems] = useState<Record<number, boolean>>({})
  const router = useRouter()
  const { setTripTitle, setTripStory, addMilestones } = useTripStore()
  
  const { submit, isLoading, object } = useObject({
    api: '/api/chat',
    schema: itinerarySchema,
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim() || isLoading) return
    submit({ prompt: input })
    setCheckedItems({})
  }

  const handleSavePlan = () => {
    if (!object?.itinerary) return

    const newMilestones = object.itinerary
      .filter((day) => day !== undefined)
      .map((day) => ({
      id: crypto.randomUUID(),
      title: `Day ${day?.day || ''}: ${day?.title || ''}`,
      content: `${day?.description || ''}\n\nActivities:\n${(day?.activities || []).map(a => `- ${a}`).join('\n')}`,
      images: [], // Images will be populated in Timeline or Memory Editor
      imageSearchQuery: day?.imageSearchQuery // Temporary field to help Memory Editor if needed
    }))

    setTripTitle('My Trip Plan')
    setTripStory('Generated by AI Travel Planner.')
    addMilestones(newMilestones)
    router.push('/memory')
  }

  const toggleCheck = (index: number) => {
    setCheckedItems(prev => ({ ...prev, [index]: !prev[index] }))
  }

  return (
    <div className="w-full max-w-2xl mx-auto flex flex-col items-center">
      <form 
        onSubmit={handleSubmit}
        className="w-full relative flex items-end gap-2 bg-white rounded-2xl shadow-sm border border-slate-200 p-2 focus-within:ring-2 focus-within:ring-[#c96442]/20 focus-within:border-[#c96442] transition-all"
      >
        <Textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Where would you like to go?"
          className="min-h-[60px] max-h-[200px] w-full resize-none border-0 shadow-none focus-visible:ring-0 text-base font-sans py-3 px-4 text-slate-900 bg-white placeholder:text-slate-400 caret-[#c96442]"
          onKeyDown={(e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
              e.preventDefault()
              handleSubmit(e)
            }
          }}
        />
        <Button 
          type="submit" 
          size="icon"
          disabled={!input.trim() || isLoading}
          className="h-12 w-12 rounded-xl bg-[#c96442] hover:bg-[#b05537] text-white shrink-0 mb-0.5 mr-0.5"
        >
          {isLoading ? (
            <Loader2 className="h-5 w-5 animate-spin" />
          ) : (
            <SendHorizontal className="h-5 w-5" />
          )}
          <span className="sr-only">Send</span>
        </Button>
      </form>
      
      <PromptChips onSelect={setInput} />

      {isLoading && <p className="mt-4 text-sm text-slate-500 animate-pulse font-sans">Generating your itinerary...</p>}
      
      {object?.checklist && object.checklist.length > 0 && (
        <div className="w-full mt-8 bg-[#fdfcf8] p-6 rounded-2xl border border-[#c96442]/20 shadow-sm text-left">
          <h3 className="font-serif text-xl font-bold text-slate-800 mb-4 flex items-center gap-2">
            <span className="text-[#c96442]">✓</span> Trip Checklist
          </h3>
          <ul className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            {object.checklist.map((item, index) => (
              <li 
                key={index} 
                className={`flex items-start gap-3 transition-colors ${checkedItems[index] ? 'text-slate-400 line-through' : 'text-slate-700'}`}
                onClick={() => toggleCheck(index)}
              >
                <Checkbox 
                  checked={checkedItems[index] || false}
                  className="mt-1 border-[#c96442]/40 data-[state=checked]:bg-[#c96442] data-[state=checked]:border-[#c96442] cursor-pointer" 
                />
                <span className="leading-snug cursor-pointer select-none">{item}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      <Timeline itinerary={object?.itinerary || []} />

      {!isLoading && object?.itinerary && object.itinerary.length > 0 && (
        <Button 
          onClick={handleSavePlan}
          className="mt-8 bg-slate-900 hover:bg-slate-800 text-white rounded-full px-8 py-6 shadow-md transition-all hover:shadow-lg hover:-translate-y-0.5 text-base"
        >
          <Save className="w-5 h-5 mr-2" />
          Save to Memory Canvas
        </Button>
      )}
    </div>
  )
}
